/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as LiveFixtureIdRouteImport } from './routes/live.$fixtureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LiveRoute,
} as any)
const LiveFixtureIdRoute = LiveFixtureIdRouteImport.update({
  id: '/$fixtureId',
  path: '/$fixtureId',
  getParentRoute: () => LiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/competitions': typeof CompetitionsRoute
  '/games': typeof GamesRoute
  '/live': typeof LiveRouteWithChildren
  '/profile': typeof ProfileRoute
  '/scout': typeof ScoutRoute
  '/squad': typeof SquadRoute
  '/live/$fixtureId': typeof LiveFixtureIdRoute
  '/live/': typeof LiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/competitions': typeof CompetitionsRoute
  '/games': typeof GamesRoute
  '/profile': typeof ProfileRoute
  '/scout': typeof ScoutRoute
  '/squad': typeof SquadRoute
  '/live/$fixtureId': typeof LiveFixtureIdRoute
  '/live': typeof LiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/competitions': typeof CompetitionsRoute
  '/games': typeof GamesRoute
  '/live': typeof LiveRouteWithChildren
  '/profile': typeof ProfileRoute
  '/scout': typeof ScoutRoute
  '/squad': typeof SquadRoute
  '/live/$fixtureId': typeof LiveFixtureIdRoute
  '/live/': typeof LiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compare'
    | '/competitions'
    | '/games'
    | '/live'
    | '/profile'
    | '/scout'
    | '/squad'
    | '/live/$fixtureId'
    | '/live/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compare'
    | '/competitions'
    | '/games'
    | '/profile'
    | '/scout'
    | '/squad'
    | '/live/$fixtureId'
    | '/live'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/compare'
    | '/competitions'
    | '/games'
    | '/live'
    | '/profile'
    | '/scout'
    | '/squad'
    | '/live/$fixtureId'
    | '/live/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  CompetitionsRoute: typeof CompetitionsRoute
  GamesRoute: typeof GamesRoute
  LiveRoute: typeof LiveRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ScoutRoute: typeof ScoutRoute
  SquadRoute: typeof SquadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof LiveRoute
    }
    '/live/$fixtureId': {
      id: '/live/$fixtureId'
      path: '/$fixtureId'
      fullPath: '/live/$fixtureId'
      preLoaderRoute: typeof LiveFixtureIdRouteImport
      parentRoute: typeof LiveRoute
    }
  }
}

interface LiveRouteChildren {
  LiveFixtureIdRoute: typeof LiveFixtureIdRoute
  LiveIndexRoute: typeof LiveIndexRoute
}

const LiveRouteChildren: LiveRouteChildren = {
  LiveFixtureIdRoute: LiveFixtureIdRoute,
  LiveIndexRoute: LiveIndexRoute,
}

const LiveRouteWithChildren = LiveRoute._addFileChildren(LiveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  CompetitionsRoute: CompetitionsRoute,
  GamesRoute: GamesRoute,
  LiveRoute: LiveRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ScoutRoute: ScoutRoute,
  SquadRoute: SquadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
