// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export function isSupabaseConfigured(): boolean {
  const url = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const key = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];
  return Boolean(url && key);
}

const NOT_CONFIGURED = 'Supabase is not configured on this environment.';

/**
 * A safe, inert client used when Supabase is not configured (missing env vars).
 *
 * The app must never hard-crash because the database isn't wired up (e.g. a
 * preview build that lacked the Vite `VITE_SUPABASE_*` build-time vars, or a
 * fresh environment before Connect DB). Every consumer degrades to the
 * guest/no-data state instead of throwing into the router error boundary:
 * `auth.getSession()` resolves to `{ session: null }`, and query builders
 * resolve to an empty `{ data: [], error: null }`.
 */
function createDegradedClient() {
  const authErr = () => ({ message: NOT_CONFIGURED });
  const auth = {
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe() {} } } }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    getSessions: () => Promise.resolve({ data: [], error: null }),
    signOut: () => Promise.resolve({ error: null }),
    setSession: () => Promise.resolve({ error: authErr() }),
    refreshSession: () => Promise.resolve({ data: { session: null }, error: authErr() }),
    signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: authErr() }),
    signInWithOtp: () => Promise.resolve({ data: { user: null, session: null }, error: authErr() }),
    signInWithOAuth: () => Promise.resolve({ data: { provider: 'google', url: null }, error: authErr() }),
    signUp: () => Promise.resolve({ data: { user: null, session: null }, error: authErr() }),
    updateUser: () => Promise.resolve({ data: { user: null }, error: authErr() }),
    onAuthStateChangeSync: () => ({ data: { session: null } }),
    initialize: () => Promise.resolve(),
  };

  // Chainable query builder that always resolves to an empty result set.
  // `q` is a callable thenable (so `await` works) that also carries the
  // chainable query-builder methods (`select`, `eq`, …) onto the same object.
  const chain = (): Record<string, unknown> => {
    const q = (() => Promise.resolve({ data: [], error: null })) as unknown as Record<string, unknown>;
    for (const m of [
      'select', 'eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'like', 'ilike', 'in',
      'is', 'contains', 'order', 'limit', 'range', 'single', 'maybeSingle',
      'insert', 'update', 'upsert', 'delete', 'match', 'or', 'not', 'filter',
    ]) {
      q[m] = chain;
    }
    q['then'] = (resolve: (v: unknown) => unknown) =>
      Promise.resolve({ data: [], error: null }).then(resolve);
    return q;
  };

  return {
    auth,
    from: () => chain(),
    rpc: () => Promise.resolve({ data: null, error: authErr() }),
    storage: {},
    functions: { invoke: () => Promise.resolve({ data: null, error: authErr() }) },
  };
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      try {
        _supabase = createSupabaseClient();
      } catch (err) {
        // Never crash the page when Supabase env is missing — degrade to guest.
        console.error('[Supabase]', err);
        console.warn('[Supabase] Running without a backend — using a degraded (guest/no-data) client.');
        _supabase = createDegradedClient() as unknown as ReturnType<typeof createSupabaseClient>;
      }
    }
    return Reflect.get(_supabase!, prop, receiver);
  },
});

